JeroenFrenken\DeserializeRequest\EventListener\DeserializeRequestEventListener:
  class: JeroenFrenken\DeserializeRequest\EventListener\DeserializeRequestEventListener
  autowire: true
  tags:
    - { name: kernel.event_listener, event: kernel.controller }
